$(document).ready(function(){
$("img#icon1").click(function(){
$("#our-design").toggle();
});
$("img#icon2").click(function(){
    $("#our-dev").toggle();
});
$("img#icon3").click(function(){
$("#our-prod").toggle();
});
});
